---
deployment:
  tasks:
    - /bin/cp -r ./dist  /home/birivcrk/public_html
    - /bin/cp -r ./bin  /home/birivcrk/public_html
    - /bin/cp -r ./svg  /home/birivcrk/public_html
    - /bin/cp -r ./db  /home/birivcrk/public_html