---
deployment:
  tasks:
    - /bin/cp -r ./dist /home/user/public_html/
    - /bin/cp -r ./bin /home/user/public_html/
    - /bin/cp -r ./svg /home/user/public_html/
    - /bin/cp -r ./db /home/user/public_html/
