---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp -r ./dist $DEPLOYPATH
    - /bin/cp -r ./bin $DEPLOYPATH
    - /bin/cp -r ./svg $DEPLOYPATH
    - /bin/cp -r ./db $DEPLOYPATH
